### ISSUE TITLE
Error setting panel state to 3:

### ISSUE THREAD

**Issue by gbrentnell** [dustindclark/homebridge-envisalink#108]
With some regular frequency - no pattern, but multiple times a day I get the following error in my Hoobs log.

Hoobs is running as version 4.2.5, Node version: 16.15.0 and Homebridge Version: 1.4.1.

Envisalink plug in is version: 1.1.1
-----------------------------
Envisalink Bridge  Envisalink  ERROR  Failed setting panel state to 3 Error: Command 04019713 resulted in 023 error from alarm
    at /var/lib/hoobs/envisalinkbridge/node_modules/homebridge-envisalink/src/platform.ts:393:28
    at Socket.<anonymous> (/var/lib/hoobs/envisalinkbridge/node_modules/nodealarmproxy/nodealarmproxy.js:316:9)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23

**Comment by kmberi** [comment]
Getting pretty much the same error when Attempting an automation to disarm the alarm every morning

**Comment by dustindclark** [comment]
`023` means you tried to disarm the system when it was already disarmed. This is expected.
