### ISSUE TITLE
Envisalink stopped responding

### ISSUE THREAD

**Issue by xtian1234** [dustindclark/homebridge-envisalink#110]
error log below. please advise.

[7/14/2022, 7:13:25 AM] [Envisalink] Caught error in zoneUpdate. Data: {
  "evtType": "zoneUpdate",
  "zone": 1,
  "code": "610",
  "status": "openrestore",
  "zoneLabel": "Zone-1"
} AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:421:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at EnvisalinkHomebridgePlatform.updateZoneAccessory (/usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:216:25)
    at EnvisalinkHomebridgePlatform.zoneUpdate (/usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:338:18)
    at EventEmitter.emit (node:events:527:28)
    at updatezone (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:160:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:294:8)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

**Comment by dustindclark** [comment]
This is a weird one...can you paste your config, removing sensitive info?

**Comment by xtian1234** [comment]
{
    "bridge": {
        "name": "Homebridge EC25",
        "username": "xxxxxxxxxxx,
        "port": xxxx,
        "pin": "xxxxxxx,
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "green",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "email": "xxxxxxxx",
            "password": "xxxxxxx",
            "platform": "myQ"
        },
        {
            "name": "Wemo",
            "mode": "auto",
            "platform": "Wemo"
        },
        {
            "host": "xxxxx",
            "password": "xxxx",
            "pin": "xxxxx",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": false,
            "suppressZoneAccessories": false,
            "suppressClockReset": true,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "House Alarm",
                    "enableChimeSwitch": false
                }
            ],
            "zones": [
                {
                    "partition": 1
                }
            ],
            "platform": "Envisalink"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxxx",
                "password": "xxxxxxx",
                "countryCode": "1",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
    ]

**Comment by xtian1234** [comment]
everything is up to date..here's the persisting error.  Seems to function o.k.

[9/22/2022, 4:32:35 PM] [Envisalink] Caught error in zoneUpdate. Data: {
  "evtType": "zoneUpdate",
  "zone": 1,
  "code": "610",
  "status": "openrestore",
  "zoneLabel": "Zone-1"
} AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:421:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at EnvisalinkHomebridgePlatform.updateZoneAccessory (/usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:216:25)
    at EnvisalinkHomebridgePlatform.zoneUpdate (/usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:338:18)
    at EventEmitter.emit (node:events:527:28)
    at updatezone (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:160:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:294:8)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

**Comment by dustindclark** [comment]
Each zone needs a name, a partition. and a type. Here's an example of one of my zones:
```
"zones": [
                {
                    "name": "Front/Back Door",
                    "partition": 1,
                    "type": "door"
                }
]
```
You can also correct this from the Homebridge UI if you don't want to manually edit the config.

**Comment by dustindclark** [comment]
In fact, these are marked as required in [the schema](https://github.com/dustindclark/homebridge-envisalink/blob/master/config.schema.json#L150)...so you must have created your config manually. It's easier just to use the UI.

**Comment by xtian1234** [comment]
I’ve had this config for about 6 years prior to confit gui being available.  So yes it was manually entered.  I’ll update config file and let u know.

**Comment by dustindclark** [comment]
This was probably introduced when I upgraded to use typescript. Either way, this workaround will avoid the issue.DustinSent from my iPhoneOn Sep 22, 2022, at 5:28 PM, xtian1234 ***@***.***> wrote:﻿
I’ve had this config for about 6 years prior to confit gui being available.  So yes it was manually entered.  I’ll update config file and let u know.

**Comment by xtian1234** [comment]
Issued resolved!  Used Scheme to update parameters.  No more errors.  Thanks
