### ISSUE TITLE
Connection error to envisalink

### ISSUE THREAD

**Issue by Einstein42** [dustindclark/homebridge-envisalink#2]
I have a DSC panel with Envisalink3.

Error Output:

```
[7/16/2016, 9:39:49 PM] Loading 1 platforms...
[7/16/2016, 9:39:49 PM] Initializing Envisalink platform...
[7/16/2016, 9:39:49 PM] Configuring Envisalink platform,  Host: 10.0.0.199, port: undefined, type: DSC
[7/16/2016, 9:39:49 PM] Starting node alarm proxy...
[7/16/2016, 9:39:49 PM] Zones: 16
[7/16/2016, 9:39:49 PM] Node alarm proxy started.  Listening for connections at: 0.0.0.0:4026
[7/16/2016, 9:39:49 PM] Initializing platform accessory 'Milne'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Front Door'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Garage to Backyard'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Door To Garage'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Lower Slider'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Upper Slider'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Downstairs Motion'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Zone 7'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Zone 8'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Cara's Window'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Collin's Window'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Chase's Window'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Master Window'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Sarah's Office Window'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'James' Office Window'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Zone 15'...
[7/16/2016, 9:39:50 PM] Initializing platform accessory 'Zone 16'...

[7/16/2016, 9:39:50 PM] Homebridge is running on port 51826.
server bound
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNRESET 10.0.0.199:4025
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
```

Config.json snippet:

```
    {
      "platform": "Envisalink",
      "host": "10.0.0.199",
      "deviceType": "DSC",
      "password": "user",
      "pin": "1234",
      "suppressZoneAccessories": false,
      "partitions": [
        {
          "name": "Alarm"
        }
      ],
      "zones": [
        {
          "name": "Front Door",
          "type": "door",
          "partition": 1
        },
        {
          "name": "Garage to Backyard",
          "type": "door",
          "partition": 1
        },
        {
          "name": "Door To Garage",
          "type": "door",
          "partition": 1
        },
        {
          "name": "Lower Slider",
          "type": "door",
          "partition": 1
        },
        {
          "name": "Upper Slider",
          "type": "door",
          "partition": 1
        },
        {
          "name": "Downstairs Motion",
          "type": "motion",
          "partition": 1
        },
        {
          "name": "Zone 7",
          "type": "door",
          "partition": 1
        },
        {
          "name": "Zone 8",
          "type": "door",
          "partition": 1
        },
        {
          "name": "Cara's Window",
          "type": "window",
          "partition": 1
        },
        {
          "name": "Collin's Window",
          "type": "window",
          "partition": 1
        },
        {
          "name": "Chase's Window",
          "type": "window",
          "partition": 1
        },
        {
          "name": "Master Window",
          "type": "window",
          "partition": 1
        },
        {
          "name": "Sarah's Office Window",
          "type": "window",
          "partition": 1
        },
        {
          "name": "James' Office Window",
          "type": "window",
          "partition": 1
        },
        {
          "name": "Zone 15",
          "type": "window",
          "partition": 1
        },
        {
          "name": "Zone 16",
          "type": "window",
          "partition": 1
        }
      ]
    }
```

**Comment by RGKS** [comment]
I'm getting the same error. Have you been able to find the fix?

**Comment by olines** [comment]
I am also getting this error.

I have a DSC panel with Envisalink4.

**Comment by zegnas11** [comment]
My Envisalink4 arrived today. installed on DSC1616 panel. My homebridge is running on the Raspberry Pi3. 

Here is the issue that is similar to (or same as) the above comments....

With homebridge-envisalink plugin, homebridge gets killed with the error "events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNRESET 192.168.1.60:4025

For now, while the plugin is active (not sure if I should remove it) I just commented out the config.json portion of the envisalink section, so the rest of the homebridge is operational. So far so good, would really love to have a working envisalink plugin and I dont have any programming skills. So am waiting.... 

Any fix is highly appreciated.

**Comment by lsmith07** [comment]
After installing the plugin (ver 0.1.3) for the first time 3 days ago, I too received this error.  For me, it was caused by my host IP entry in config.json: I had "10.0.1.024" instead of "10.0.1.24".  Once I corrected it the plugin loaded and homebridge stayed connected.  If you haven't already, I suggest validating your Envisalink's IP address by entering it into your browser to log in with the user/user default credentials.  You should do this anyhow to change the default password from "user" (just don't forget to update your config.json file after doing so).  Also, you should set Envisalink's IP to static (or DHCP reserved), to avoid it changing and introducing a connection issue again.  I also suggest updating the plugin to the latest version (0.1.4); it resolves a secondary issue I encountered after getting past this connection issue.  Here's a link for obtaining Envisalink's IP address if the one you have is incorrect or has changed: http://www.eyezon.com/AccessingEnvisalinkApplicationNoteEZ.pdf.

**Comment by dustindclark** [comment]
Closing out really old issue that is not recreatable on current version of NodeAlarmProxy and HomeBridge.  Please re-open if this issue persists.
