### ISSUE TITLE
Honeywell: Alarm request did not return successfully in allocated time.

### ISSUE THREAD

**Issue by mtw13** [dustindclark/homebridge-envisalink#228]
Suddenly, I cannot change the alarm state (arm or disarm) using HomeKit. The envisalink app works perfectly - but homebridge forces a reboot of the homebridge-envisalink child bridge every time I try to change. 

[22/02/2023, 23:00:24] [Alarm] Arming alarm to Stay (Home). [Partition 1]
[22/02/2023, 23:00:24] [Alarm] setAlarmState: Partition state command issued.
[22/02/2023, 23:00:24] [Alarm] !WARNING! PIN/CODE may appear in the clear TX >  xxxxx
[22/02/2023, 23:00:24] [homebridge-envisalink-ademco] Characteristic 'Security System Target State': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[22/02/2023, 23:00:24] [homebridge-envisalink-ademco] Error: 
    at SecuritySystemTargetState.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2627:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at EnvisalinkPartitionAccessory.setTargetState (/usr/local/lib/node_modules/homebridge-envisalink-ademco/accessories/partitionAccessory.js:201:16)
    at SecuritySystemTargetState.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink-ademco/accessories/partitionAccessory.js:68:52)
    at SecuritySystemTargetState.emit (node:events:520:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2596:16
    at new Promise (<anonymous>)
    at SecuritySystemTargetState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2594:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
[22/02/2023, 23:00:24] [Alarm] Command | %00,01,1C08,08,00, Home    Ready to Arm  $,00,01,1C08,08,00, Home    Ready to Arm   | Acknowledged
[22/02/2023, 23:00:24] [Alarm] Envisakit Operation: updatekeypad
[22/02/2023, 23:00:24] [Alarm] systemUpdate: Status changed -  {
  partition: '01',
  code: {
    icon: [ 3, 10, 11, 12 ],
    zone: '08',
    beep: 'off',
    txt: "Home    Ready to Arm  "
  },
  status: 'Virtual Keypad Update',
  keypadledstatus: {
    alarm: false,
    alarm_in_memory: false,
    armed_away: false,
    ac_present: true,
    bypass: false,
    chime: false,
    not_used1: false,
    armed_zero_entry_delay: false,
    alarm_fire_zone: false,
    system_trouble: false,
    not_used2: true,
    not_used3: true,
    ready: true,
    fire: false,
    low_battery: false,
    armed_stay: false
  },
  mode: 'READY'
}
[22/02/2023, 23:00:26] [Alarm] Command | %00,01,1C08,08,00,Home    Ready to Arm  $,00,01,1C08,08,00,Home    Ready to Arm   | Acknowledged
[22/02/2023, 23:00:26] [Alarm] Envisakit Operation: updatekeypad
[22/02/2023, 23:00:26] [Alarm] systemUpdate: Status changed -  {
  partition: '01',
  code: {
    icon: [ 3, 10, 11, 12 ],
    zone: '08',
    beep: 'off',
    txt: "Home    Ready to Arm  "
  },
  status: 'Virtual Keypad Update',
  keypadledstatus: {
    alarm: false,
    alarm_in_memory: false,
    armed_away: false,
    ac_present: true,
    bypass: false,
    chime: false,
    not_used1: false,
    armed_zero_entry_delay: false,
    alarm_fire_zone: false,
    system_trouble: false,
    not_used2: true,
    not_used3: true,
    ready: true,
    fire: false,
    low_battery: false,
    armed_stay: false
  },
  mode: 'READY'
}
[22/02/2023, 23:00:34] [Alarm] Alarm request did not return successfully in allocated time. Current alarm status is READY

/usr/local/lib/node_modules/homebridge-envisalink-ademco/accessories/partitionAccessory.js:126
        setAlarmState();
        ^
ReferenceError: setAlarmState is not defined
    at EnvisalinkPartitionAccessory.processAlarmTimer (/usr/local/lib/node_modules/homebridge-envisalink-ademco/accessories/partitionAccessory.js:126:9)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[22/02/2023, 23:00:34] [Alarm] Child bridge process ended
[22/02/2023, 23:00:34] [Alarm] Process Ended. Code: 1, Signal: null
[22/02/2023, 23:00:41] [Alarm] Restarting Process...

**Comment by mtw13** [comment]
I should add that I am notified of all alarms through HomeKit - so it is clearly communicating - but I cannot arm or disarm.
