### ISSUE TITLE
Add Support for Envisalink UNO mode

### ISSUE THREAD

**Issue by g1gem** [dustindclark/homebridge-envisalink#251]
Envisalink can operate without a 3rd party alarm system, they call it Envisalink UNO.  It has its own expansion modules.  It is a great way to monitor contact closures and trigger relays.

https://www.eyezon.com/uno.php

Can you add support for this?

Thanks and Gig'em

**Comment by g1gem** [comment]
Error when trying to connect to Envisalink that is running in standalone mode.  (no DSC panel, they call it UNO mode)...

3/27/2023, 4:00:16 PMEnvisalink BridgeEnvisalinkConfiguring Envisalink platform,  Host: 192.168.1.79 Port: 4025
3/27/2023, 4:00:16 PMEnvisalink BridgeEnvisalinkAttempting connect to Envisalink..
3/27/2023, 4:00:16 PMEnvisalink BridgeEnvisalinkStarting Envisalink connection...
3/27/2023, 4:00:16 PMEnvisalink BridgeEnvisalinkNode alarm proxy started.  Listening for connections at: 0.0.0.0:4026
3/27/2023, 4:00:16 PMEnvisalink BridgeEnvisalinkPanic buttons disabled. Will not install panic switches.
3/27/2023, 4:00:16 PMEnvisalink BridgeBridge is running on port 51856.
3/27/2023, 4:00:26 PMEnvisalink BridgeEnvisalinkAttempting connect to Envisalink..
3/27/2023, 4:00:26 PMEnvisalink BridgeEnvisalinkERRORCaught connection error. Sleeping 60 seconds and trying again.  Error: Unknown disconnect occurred.
    at EnvisalinkHomebridgePlatform.handleDisconnect (/var/lib/hoobs/envisalinkbridge/node_modules/homebridge-envisalink/src/platform.ts:123:30)
    at EventEmitter.emit (node:events:513:28)
    at Socket.<anonymous> (/var/lib/hoobs/envisalinkbridge/node_modules/nodealarmproxy/nodealarmproxy.js:345:16)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
3/27/2023, 4:00:27 PMEnvisalink BridgeEnvisalinkERROREnvisalink actual disconnected
3/27/2023, 4:01:27 PMEnvisalink BridgeEnvisalinkStarting Envisalink connection...
