### ISSUE TITLE
Error when setting current time

### ISSUE THREAD

**Issue by michaelkedwards** [dustindclark/homebridge-envisalink#26]
I'm getting the following error when running homebridge:

```
[11/25/2017, 11:51:35 AM] Homebridge is running on port 51826.
actual disconnected
[11/25/2017, 11:51:38 AM] [Envisalink] Setting the current time on the alarm system to: 1151112517
sendcommand 01011511125178A
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:284:12)
    at sendcommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:253:12)
    at Object.exports.manualCommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:263:3)
    at EnvisalinkAccessory.processTimeChange (/usr/local/lib/node_modules/homebridge-envisalink/index.js:460:9)
    at EnvisalinkAccessory.processDelayedEvents (/usr/local/lib/node_modules/homebridge-envisalink/index.js:516:18)
    at Timer.listOnTimeout (timers.js:92:15)

```

Running the latest version of homebridge 0.4.33

**Comment by michaelkedwards** [comment]
I resolved the issue by setting `suppressClockReset` to true...sorry I did not read update correctly
