### ISSUE TITLE
Getting error whenever I change state of alarm

### ISSUE THREAD

**Issue by michaelkedwards** [dustindclark/homebridge-envisalink#27]
Whenever I attempt to arm the system I get the following error:
```
11/25/2017, 1:06:38 PM] [Envisalink] Attempting to set alarm state to:  1
[11/25/2017, 1:06:38 PM] [Envisalink] Arming alarm to Away.
sendcommand 0301C4
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:284:12)
    at sendcommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:253:12)
    at Object.exports.manualCommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:263:3)
    at EnvisalinkAccessory.processAlarmState (/usr/local/lib/node_modules/homebridge-envisalink/index.js:426:17)
    at EnvisalinkAccessory.processDelayedEvents (/usr/local/lib/node_modules/homebridge-envisalink/index.js:514:18)
    at Timer.listOnTimeout (timers.js:92:15)
```

This occurs whenever I change the state of the alarm. My other homebridge accessories are functioning as expected.

**Comment by mpreissner** [comment]
I'm getting a similar error.  Using latest version of HomeBridge and homebridge-envisalink with an EVL4.  Every time I try to change the alarm state, homebridge crashes and respawns, and the alarm doesn't change state.

```
12:51:00 - [Envisalink] Attempting to set alarm state to:  0
12:51:00 - [Envisalink] Arming alarm to Stay/Night.
12:51:00 - sendcommand 0311C5
12:51:00 - Unhandled Error Detected :  Error: This socket is closed
    at Socket._writeGeneric (net.js:726:18)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at sendcommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:253:12)
    at Object.exports.manualCommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:263:3)
    at EnvisalinkAccessory.processAlarmState (/usr/local/lib/node_modules/homebridge-envisalink/index.js:433:17)
    at EnvisalinkAccessory.processDelayedEvents (/usr/local/lib/node_modules/homebridge-envisalink/index.js:521:18)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
12:51:00 - Restarting homebridge due to an error
12:51:00 - restarting...
12:51:00 - shutting down...
12:51:00 - shutting down servers...
```
Also, my main partition shows up in the Home App fine, but it says Obstruction Detected when my panel is reading ready.

I also have a Vera home controller that monitors the Envisalink, and it has no trouble remote-arming/disarming the DSC.

**Comment by mpreissner** [comment]
Ok, just figured it out.  The issue is a limitation of the Envisalink board.  It will only accept one client at a time, so with the Vera connected to it, the HomeBridge was unable to connect.  Once I unplugged my Vera, HomeBridge connected, and I can change the alarm state without issue.  Also, my sensors now update their status in the Home and Eve apps.

I'm thinking this also was why HomeBridge crashed when I had the time update enabled in the config...I'll have to turn off the time update suppression and see what happens.

**Comment by adrianmihalko** [comment]
I suggest you to use Alarmserver as a middle client:

https://github.com/juggie/AlarmServer

It does have a proxy feature, where you can connect any number of users:

## Run a proxy for the Envisalink device to get around the 1 connection limit

**Comment by michaelkedwards** [comment]
This issue can be closed now. Thank you.
