### ISSUE TITLE
Custom Command Issue - Button status resetting

### ISSUE THREAD

**Issue by scoutbeer** [dustindclark/homebridge-envisalink#272]
I'm trying to use the Custom Command capabilities to create a toggle swtich that when set to ON will send a command to bypass a zone.  The goal here is to bypass a zone **_before_** it's status is Open.

I can see the toggle switch created in HomeKit.  I'm able to click the toggle switch on and see the command received at the panel and change the zone state to bypassed.  

The challenge I have is the toggle button in HomeKit won't stay in the ON  status when the zone is bypassed.  It continues to reset its state immediately after it is triggered (back to OFF). 

If I press the toggle ON again the command sends to the panel and it changes it the bypass status for that Zone back to the normal state.

I'm trying to figure out how I can keep the Toggle switch to stay in the ON state when the Zone is Bypassed and in the OFF state when the Zone is in normal state.

**Logs:**

```
[19/04/2023, 11:30:08] [homebridge-envisalink] Invoking custom command: 0711*105#
[19/04/2023, 11:30:08] [homebridge-envisalink] Sending command to NAP 0711*105#
[19/04/2023, 11:30:08] [homebridge-envisalink] sendcommand 0711*105#AC
[19/04/2023, 11:30:08] [homebridge-envisalink] Command 071 Acknowledged
[19/04/2023, 11:30:08] [homebridge-envisalink] Command 0711*105# succeeded.
[19/04/2023, 11:30:08] [homebridge-envisalink] Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[19/04/2023, 11:30:08] [homebridge-envisalink] Error: 
    at On.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at On.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2557:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[19/04/2023, 11:30:08] [homebridge-envisalink] Keypad LED State: 80 
[19/04/2023, 11:30:08] [homebridge-envisalink] Keypad LED Flash State: 08 
[19/04/2023, 11:30:10] [homebridge-envisalink] Keypad LED Flash State: 00 
[19/04/2023, 11:30:10] [homebridge-envisalink] Keypad LED State: 81 
[19/04/2023, 11:30:10] [homebridge-envisalink] Partition 1 Ready
[19/04/2023, 11:30:10] [homebridge-envisalink] Inside partitionUpdate: {
  "evtType": "partitionUpdate",
  "partition": 1,
  "code": "650",
  "status": "ready"
}
[19/04/2023, 11:30:10] [homebridge-envisalink] Restoring existing partition accessory from cache: Wilmot
[19/04/2023, 11:30:10] [homebridge-envisalink] Setting accessory details for partition: {
  "name": "Home",
  "number": 1,
  "enableChimeSwitch": true,
  "chimeCommand": "0711*4",
  "chimeActive": false,
  "pin": "xxxxxxx",
  "status": {
    "shortCode": "650",
    "longCode": "650",
    "description": "Partition Ready",
    "text": "ready",
    "action": "updatepartition",
    "verbSuffix": "Ready"
  },
  "bypassEnabled": false
}
[19/04/2023, 11:30:10] [homebridge-envisalink] Partition 1: ready, mode: undefined.
[19/04/2023, 11:30:10] [homebridge-envisalink] Setting current state to 3
[19/04/2023, 11:30:10] [homebridge-envisalink] Setting target state to 3
[19/04/2023, 11:30:10] [homebridge-envisalink] Home Ready
```

**Plugin Config:**

```json

{
            "host": "XXX.XXX.XXX.XXX",
            "password": "XXXXXXXXXXx",
            "pin": "XXXXX",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": true,
            "suppressZoneAccessories": false,
            "suppressClockReset": true,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Home",
                    "enableChimeSwitch": true,
                    "pin": "XXXXX"
                }
            ],
            "zones": [
                {
                    "name": "Living Room Motion",
                    "partition": 1,
                    "zoneNumber": 4,
                    "type": "motion"
                },
                {
                    "name": "Family Room Motion",
                    "partition": 1,
                    "zoneNumber": 5,
                    "type": "motion"
                },
                {
                    "name": "Basement Motion",
                    "partition": 1,
                    "zoneNumber": 6,
                    "type": "motion"
                }
            ],
            "customCommands": [
                {
                    "name": "Bypass Family Room",
                    "command": "0711*105#"
                },
              ],
            "_bridge": {
                "username": "0E:F5:9B:72:09:DE",
                "port": 47646
            },
            "platform": "Envisalink"
        },
```

**Environment:**

* **Plugin Version**: v1.2.10
* **Homebridge Version**: v1.6.0
* **Node.js Version**: v18.13.0
* **Operating System**: Raspbian

**Comment by dustindclark** [comment]
Custom commands aren't stateful, so this wouldn't work without supporting code that is specific to bypassing zones.Have you tried out the existing bypass switch? If on, any open zones will be bypassed before arming the alarm.DustinSent from my iPhoneOn Apr 19, 2023, at 11:49 AM, scoutbeer ***@***.***> wrote:﻿
I'm trying to use the Custom Command capabilities to create a toggle swtich that when set to ON will send a command to bypass a zone.  The goal here is to bypass a zone before it's status is Open.
I can see the toggle switch created in HomeKit.  I'm able to click the toggle switch on and see the command received at the panel and change the zone state to bypassed.
The challenge I have is the toggle button in HomeKit won't stay in the ON  status when the zone is bypassed.  It continues to reset its state immediately after it is triggered (back to OFF).
If I press the toggle ON again the command sends to the panel and it changes it the bypass status for that Zone back to the normal state.
I'm trying to figure out how I can keep the Toggle switch to stay in the ON state when the Zone is Bypassed and in the OFF state when the Zone is in normal state.
Logs:
[19/04/2023, 11:30:08] [homebridge-envisalink] Invoking custom command: 0711*105#
[19/04/2023, 11:30:08] [homebridge-envisalink] Sending command to NAP 0711*105#
[19/04/2023, 11:30:08] [homebridge-envisalink] sendcommand 0711*105#AC
[19/04/2023, 11:30:08] [homebridge-envisalink] Command 071 Acknowledged
[19/04/2023, 11:30:08] [homebridge-envisalink] Command 0711*105# succeeded.
[19/04/2023, 11:30:08] [homebridge-envisalink] Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[19/04/2023, 11:30:08] [homebridge-envisalink] Error: 
    at On.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at On.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2557:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[19/04/2023, 11:30:08] [homebridge-envisalink] Keypad LED State: 80 
[19/04/2023, 11:30:08] [homebridge-envisalink] Keypad LED Flash State: 08 
[19/04/2023, 11:30:10] [homebridge-envisalink] Keypad LED Flash State: 00 
[19/04/2023, 11:30:10] [homebridge-envisalink] Keypad LED State: 81 
[19/04/2023, 11:30:10] [homebridge-envisalink] Partition 1 Ready
[19/04/2023, 11:30:10] [homebridge-envisalink] Inside partitionUpdate: {
  "evtType": "partitionUpdate",
  "partition": 1,
  "code": "650",
  "status": "ready"
}
[19/04/2023, 11:30:10] [homebridge-envisalink] Restoring existing partition accessory from cache: Wilmot
[19/04/2023, 11:30:10] [homebridge-envisalink] Setting accessory details for partition: {
  "name": "Home",
  "number": 1,
  "enableChimeSwitch": true,
  "chimeCommand": "0711*4",
  "chimeActive": false,
  "pin": "xxxxxxx",
  "status": {
    "shortCode": "650",
    "longCode": "650",
    "description": "Partition Ready",
    "text": "ready",
    "action": "updatepartition",
    "verbSuffix": "Ready"
  },
  "bypassEnabled": false
}
[19/04/2023, 11:30:10] [homebridge-envisalink] Partition 1: ready, mode: undefined.
[19/04/2023, 11:30:10] [homebridge-envisalink] Setting current state to 3
[19/04/2023, 11:30:10] [homebridge-envisalink] Setting target state to 3
[19/04/2023, 11:30:10] [homebridge-envisalink] Home Ready

Plugin Config:
{
            "host": "XXX.XXX.XXX.XXX",
            "password": "XXXXXXXXXXx",
            "pin": "XXXXX",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": true,
            "suppressZoneAccessories": false,
            "suppressClockReset": true,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Home",
                    "enableChimeSwitch": true,
                    "pin": "XXXXX"
                }
            ],
            "zones": [
                {
                    "name": "Living Room Motion",
                    "partition": 1,
                    "zoneNumber": 4,
                    "type": "motion"
                },
                {
                    "name": "Family Room Motion",
                    "partition": 1,
                    "zoneNumber": 5,
                    "type": "motion"
                },
                {
                    "name": "Basement Motion",
                    "partition": 1,
                    "zoneNumber": 6,
                    "type": "motion"
                }
            ],
            "customCommands": [
                {
                    "name": "Bypass Family Room",
                    "command": "0711*105#"
                },
              ],
            "_bridge": {
                "username": "0E:F5:9B:72:09:DE",
                "port": 47646
            },
            "platform": "Envisalink"
        },
Environment:

Plugin Version: v1.2.10
Homebridge Version: v1.6.0
Node.js Version: v18.13.0
Operating System: Raspbian

**Comment by scoutbeer** [comment]
> Custom commands aren't stateful

@dustindclark, thank you for the quick reply.  This now makes sense after learning that the Custom Commands are not stateful.

The existing Bypass switch will not work for my use case.  I'm specifically looking to bypass some of the motion zones.  I believe that means i'd have to trigger all the specific motion zones to be 'open' at the time of using the Bypass Switch.  I'm not sure how i'd accomplish that.   

If there is an alternative option to configure specific zones in conjunction with the existing Bypass switch implementation then that would probably work for me.  Thoughts?

**Comment by dustindclark** [comment]
Interesting use case. May need to resurrect the feature request for bypassing individual zones. Closed that in favor of a single bypass switch.

I generally use "Home" to arm the alarm without motion and "Away" to arm the motion alarms. Is that not how your panel is programmed? If not, why?

**Comment by scoutbeer** [comment]
> Interesting use case. May need to resurrect the feature request for bypassing individual zones. Closed that in favor of a single bypass switch.

I'd be in favor of this as it would solve my use case.



> I generally use "Home" to arm the alarm without motion and "Away" to arm the motion alarms.

In general, this is likely the correct approach.  However in my use case, I want to disable motion while away so that a pet doesn't set off the alarm.  Thoughts?
