### ISSUE TITLE
Problems with a new envisalink duo install

### ISSUE THREAD

**Issue by ryarber** [dustindclark/homebridge-envisalink#291]
**Describe Your Problem:**
We just finished building a home. We had a honeywell vista 20p security panel installed and I just hooked up an envisalink duo. Trying to get homebridge working with it. I've gone through all the honeywell configuration of it and all the error messages are gone on the app.
Homebridge doesn't seem to be able to communicate with it.

I see others have had similar problems. I've checked the password matches. This is a new install and this is the first device to connect to the DUO so there should be no other devices using the port. I've turned off pihole. I've rebooted the DUO, etc.
My firmware on the DUO is 01.00.95A.

My router is a Unifi UDM SE. The device is hardwired to my unifi switch

**Logs:**
[22/05/2024, 21:56:03] [Envisalink] Caught connection error. Sleeping 60 seconds and trying again.  Error: Unknown disconnect occurred.
    at EnvisalinkHomebridgePlatform.handleDisconnect (/var/lib/homebridge/node_modules/homebridge-envisalink/src/platform.ts:123:30)
    at EventEmitter.emit (node:events:517:28)
    at Socket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:345:16)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[22/05/2024, 21:56:03] [Envisalink] Envisalink actual disconnected

**Plugin Config:**

        {
            "host": "192.168.1.xxx",
            "password": "xxxxxx",
            "pin": "xxxx",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": true,
            "suppressZoneAccessories": false,
            "suppressClockReset": true,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Home",
                    "enableChimeSwitch": false,
                    "pin": "xxxx"
                }
            ],
            "zones": [
                {
                    "name": "Smoke",
                    "partition": 1,
                    "zoneNumber": 1,
                    "type": "smoke"
                },
                {
                    "name": "Side Entry",
                    "partition": 1,
                    "zoneNumber": 2,
                    "type": "door"
                },
                {
                    "name": "Carport Door",
                    "partition": 1,
                    "zoneNumber": 3,
                    "type": "door"
                },
                {
                    "name": "Back Porch Door",
                    "partition": 1,
                    "zoneNumber": 4,
                    "type": "door"
                },
                {
                    "name": "Front Door",
                    "partition": 1,
                    "zoneNumber": 5,
                    "type": "door"
                },
                {
                    "name": "Living Room Motion",
                    "partition": 1,
                    "zoneNumber": 6,
                    "type": "motion"
                },
                {
                    "name": "Kitchen Window",
                    "partition": 1,
                    "zoneNumber": 9,
                    "type": "window"
                },
                {
                    "name": "Living Room Window Left",
                    "partition": 1,
                    "zoneNumber": 10,
                    "type": "window"
                },
                {
                    "name": "Living Room Window Center",
                    "partition": 1,
                    "zoneNumber": 11,
                    "type": "window"
                },
                {
                    "name": "Living Room Window Right ",
                    "partition": 1,
                    "zoneNumber": 12,
                    "type": "window"
                },
                {
                    "name": "Master BR Window Left",
                    "partition": 1,
                    "zoneNumber": 13,
                    "type": "window"
                },
                {
                    "name": "Master BR Window Center",
                    "partition": 1,
                    "zoneNumber": 14,
                    "type": "window"
                },
                {
                    "name": "Master BR Window Right",
                    "partition": 1,
                    "zoneNumber": 15,
                    "type": "window"
                },
                {
                    "name": "Laundry Window",
                    "partition": 1,
                    "zoneNumber": 16,
                    "type": "window"
                },
                {
                    "name": "Bedroom 1 Window",
                    "partition": 1,
                    "zoneNumber": 17,
                    "type": "window"
                },
                {
                    "name": "Bedroom 2 Window Left",
                    "partition": 1,
                    "zoneNumber": 18,
                    "type": "window"
                },
                {
                    "name": "Bedroom 2 Window Right",
                    "partition": 1,
                    "zoneNumber": 19,
                    "type": "window"
                },
                {
                    "name": "Dining Rm Window L",
                    "partition": 1,
                    "zoneNumber": 20,
                    "type": "window"
                },
                {
                    "name": "Dining Rm Window Right",
                    "partition": 1,
                    "zoneNumber": 21,
                    "type": "window"
                },
                {
                    "name": "Bedroom 3 Window",
                    "partition": 1,
                    "zoneNumber": 22,
                    "type": "window"
                },
                {
                    "name": "Shop Motion",
                    "partition": 1,
                    "zoneNumber": 23,
                    "type": "motion"
                },
                {
                    "name": "Shop Door",
                    "partition": 1,
                    "zoneNumber": 24,
                    "type": "door"
                }
            ],
            "platform": "Envisalink"
        },

**Screenshots:**

**Environment:**
Raspberry Pi 4

* **Plugin Version**:
* 1.2.10. I also tried 1.2.9
* **Homebridge Version**: 1.8.2
* **Node.js Version**: 18.19.0
* **NPM Version**: 10.2.3
* **Operating System**: Raspbian GNU/Linux Bullseye (11)

**Comment by ryarber** [comment]
My JSON file seems different than older versions i've seen. For one, there's no line for device type. Platform is listed at the bottom.

**Comment by ryarber** [comment]
I’ve looked all over settings for my udm pro router and cannot see where udp is being blocked. My TPI on the envisalink does not show anything being connected. I’ve also tried updating node.js to most recent. I’ve downgraded to different versions of plugin, most recently 1.2.6. I also tried 1.2.9

**Comment by ryarber** [comment]
Is this plugin deprecated? The lack of any response makes me think so.
