### ISSUE TITLE
Failed setting panel state to 3 Error after Homebridge update to v4.61.0

### ISSUE THREAD

**Issue by SourLemons5** [dustindclark/homebridge-envisalink#293]
**Describe The Bug:**
The Home app is unresponsive but is sending commands to Homebridge, the Alarm panel will eventually respond but will execute all the commands tapped on from the unresponsive home app in sequence after a delay.

**To Reproduce:**
Seeing the behavior on Homebridge v4.61.0 and iOS18, using an Apple 4k TV as the hub

**Expected behavior:**
Responds to commands sent

**Logs:**
Multiple of below for every command regardless (as far as i can tell) of the command sent (NIGHT, AWAY or HOME)

[10/14/2024, 7:08:16 PM] [homebridge-envisalink] Failed setting panel state to 3 Error: Command 0401[pin] resulted in error from alarm: 023: API System Not Armed (sent in response to a disarm command)
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/homebridge/node_modules/homebridge-envisalink/src/platform.ts:483:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EnvisalinkPartitionAccessory.setPanelState (/homebridge/node_modules/homebridge-envisalink/src/partitionAccessory.ts:213:13)

**Plugin Config:**

"host": "x.x.x.x",
    "password": "pwd",
    "pin": "xxxx",
    "port": 4025,
    "proxyPort": 4026,
    "enableVerboseLogging": true,
    "suppressZoneAccessories": false,
    "suppressClockReset": false,
    "policePanic": {
        "enabled": false,
        "name": "Police Panic"
    },
    "ambulancePanic": {
        "enabled": false,
        "name": "Ambulance Panic"
    },
    "firePanic": {
        "enabled": false,
        "name": "Fire Panic"
    },
    "partitions": [
        {
            "name": "Alarm",
            "enableChimeSwitch": true
        }
    ],
    "zones": [
        {
            "name": "Zone 1",
            "partition": 1,
            "type": "door"
        },
        {
            "name": "Zone 2",
            "partition": 1,
            "type": "door"
        },
        {
            "name": "Zone 3",
            "partition": 1,
            "type": "door"
        },
        {
            "name": "Zone 4",
            "partition": 1,
            "type": "door"
        },
        {
            "name": "Zone 5",
            "partition": 1,
            "type": "motion"
        },
        {
            "name": "Zopne 6",
            "partition": 1,
            "type": "motion"
        },
        {
            "name": "Zone 7",
            "partition": 1,
            "type": "door"
        },
        {
            "name": "Zone 8",
            "partition": 1,
            "type": "door"
        }
    ],
    "_bridge": {
        "username": "xxxxx",
        "port": xxxx
    },
    "platform": "Envisalink"

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.2.10
* **Homebridge Version**: v4.6.10
* **Node.js Version**: v20.18.0
* **NPM Version**: v10.8.2
* **Operating System**: Docker

**Comment by zaxx40** [comment]
same here
