### ISSUE TITLE
Envisalink on Vista20p issues

### ISSUE THREAD

**Issue by pinkchry** [dustindclark/homebridge-envisalink#35]
I get the following error when attempting to arm the system. I'm capable of editing the *.js files and debugging the system. If you can give me a pointer on getting started, that would be great. 
Thanks!

[2018-2-13 03:57:53] [Envisalink] Initializing Envisalink platform...
[2018-2-13 03:57:53] [Envisalink] Configuring Envisalink platform,  Host: 192.168.1.xxx, port: 4025, type: HoneyWell
[2018-2-13 03:57:53] [Envisalink] Starting node alarm proxy...
[2018-2-13 03:57:53] [Envisalink] Zones: 3
[2018-2-13 03:57:53] [Envisalink] User Programs: null
[2018-2-13 03:57:53] [Envisalink] Node alarm proxy started.  Listening for connections at: 0.0.0.0:4026
[2018-2-13 03:57:53] [Envisalink] Initializing platform accessory 'Indoor'...
[2018-2-13 03:57:54] [Envisalink] Initializing platform accessory 'Outdoor'...
[2018-2-13 03:57:54] Loading 0 accessories...
...
[2018-2-13 04:02:53] [Envisalink] Attempting to set alarm state to:  0
[2018-2-13 04:02:53] [Envisalink] Arming alarm to Stay/Night.
sendcommand 0311C5
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at sendcommand (/homebridge/node_modules/nodealarmproxy/nodealarmproxy.js:253:12)
    at Object.exports.manualCommand (/homebridge/node_modules/nodealarmproxy/nodealarmproxy.js:263:3)
    at EnvisalinkAccessory.processAlarmState (/homebridge/node_modules/homebridge-envisalink/index.js:433:17)
    at EnvisalinkAccessory.processDelayedEvents (/homebridge/node_modules/homebridge-envisalink/index.js:521:18)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.

The config file is as follows

        {
            "platform": "Envisalink",
            "host": "192.168.1.xxx”,
            "deviceType": "HoneyWell",
            "password": "xxxxx",
            "port": "4025",
            "pin": xxxx,
            "suppressZoneAccessories": true,
            "suppressClockReset": true,
            "partitions": [
                {
                    "name": "Indoor"
                },
                {
                    "name": "Outdoor"
                }
            ],
            "zones": [
                {
                    "name": "Front Room Motion",
                    "type": "motion",
                    "partition": 1,
                    "zoneNumber": 9
                },
                {
                    "name": "Front Door",
                    "type": "door",
                    "partition": 1,
                    "zoneNumber": 14
                },
                {
                    "name": "Kitchen Window",
                    "type": "window",
                    "partition": 1,
                    "zoneNumber": 17
                }
            ]
        }

**Comment by dstapleton92** [comment]
Hi! This is the same thing going on in issue #34  

At this time, the plugin is not compatible with Envisalink variants connected to Honeywell/Ademco panels.

**Comment by dustindclark** [comment]
Closing as dupe in favor of #59.
