### ISSUE TITLE
Error & Homebridge crashes when disarming alarm

### ISSUE THREAD

**Issue by rvs007** [dustindclark/homebridge-envisalink#42]
I get this error in homebridge when I try to disarm the alarm (either by Siri or using the Home app):

`/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at Object.callback (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13)
    at /usr/lib/node_modules/homebridge-envisalink/index.js:448:31
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:222:54)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
`

Homebridge crashes after this error.  Arming the alarm works fine.  Does anyone have any solutions?

**Comment by dustindclark** [comment]
Fixed and published in 0.2.4.
