### ISSUE TITLE
'Envisalink' was not registered 

### ISSUE THREAD

**Issue by Rio-D** [dustindclark/homebridge-envisalink#44]
Hi,

Attempting to get this to work with Envisalink 4 but am having trouble.

I installed it using npm along with nodealarmproxy.

However when I try to start home bridge I get the following error.

Error: The requested platform 'Envisalink' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by Rio-D** [comment]
nvm! Solved.

Needed to install with -g like I did homebridge so it was all in the same location. Looks like everything is working!! :D
