### ISSUE TITLE
Homebridge Config UI X 4.17.1 and above break my homebridge-envisalink 

### ISSUE THREAD

**Issue by gruv2ths** [dustindclark/homebridge-envisalink#53]
Ever since i updated my Homebridge Config UI X to 4.18.0 then 4.19.0 i cannot get homebridge-envisalink to load correctly.
My configuration is below, so is the error. Any help would be amazing. Thanks!

{
    "bridge": {
        "name": "Homebridge BCDB",
        "username": "**********",
        "port": 51671,
        "pin": "*******"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "InsteonLocal",
            "name": "Insteon Local Platform",
            "user": "********",
            "pass": "********",
            "host": "10.0.1.13",
            "port": "25105",
            "model": "2245",
            "refresh": "0",
            "server_port": "3000",
            "keepAlive": "3600",
            "devices": [
                {
                    "name": "Family Room Fan Light",
                    "deviceID": "43.ED.27",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Front Patio Lights",
                    "deviceID": "49.D8.1F",
                    "dimmable": "no",
                    "deviceType": "switch"
                }
            ]
        },
        {
            "platform": "Envisalink",
            "host": "*******",
            "deviceType": "DSC",
            "password": "user",
            "pin": "*******",
            "suppressZoneAccessories": false,
            "suppressClockReset": false,
            "partitions": [
                {
                    "name": "Alarm"
                }
            ],
            "zones": [
                {
                    "name": "Front/Back Door",
                    "type": "door",
                    "partition": 1
                },
                {
                    "name": "Downstairs Windows",
                    "type": "window",
                    "partition": 1
                },
                {
                    "name": "Patio Door",
                    "type": "door",
                    "partition": 1
                },
                {
                    "name": "Master Bedroom Windows",
                    "type": "window",
                    "partition": 1
                },
                {
                    "name": "Upstairs Windows",
                    "type": "windows",
                    "partition": 1
                }
            ]
        }
    ]
}

[5/14/2020, 10:23:28] Homebridge is running on port 51671.
[5/14/2020, 10:23:31] Error: connect EHOSTUNREACH 10.0.1.48:4025
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
[5/14/2020, 10:23:31] Got SIGTERM, shutting down Homebridge...
[5/14/2020, 10:23:33] [Envisalink] Setting the current time on the alarm system to: 1023051420
sendcommand 010102305142083
[5/14/2020, 10:23:33] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at sendcommand (/usr/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:253:12)
    at Object.exports.manualCommand (/usr/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:263:3)
    at EnvisalinkAccessory.processTimeChange (/usr/lib/node_modules/homebridge-envisalink/index.js:471:9)
    at EnvisalinkAccessory.processDelayedEvents (/usr/lib/node_modules/homebridge-envisalink/index.js:527:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[5/14/2020, 10:23:36] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/14/2020, 10:23:40] [Config] Changes to config.json saved.
[5/14/2020, 10:23:41] [Config] Homebridge restart request received

**Comment by gruv2ths** [comment]
My EyezOn somehow changed IP addresses probably due to DHCP right when the UI was updated..
