### ISSUE TITLE
Envisalink Firmware Updated

### ISSUE THREAD

**Issue by erfind** [dustindclark/homebridge-envisalink#67]
I updated my firmware and now I’m having issues with the plugin. Here are my error logs when attempting to arm my system. 

[3/16/2021, 23:59:37] [Envisalink] Attempting to set alarm state on partition 1 Home to 1 AWAY_ARM
[3/16/2021, 23:59:37] [Envisalink] Arming alarm to Away.
[3/16/2021, 23:59:37] Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:454:14)
    at sendcommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:253:12)
    at Object.exports.manualCommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:263:3)
    at EnvisalinkAccessory.processAlarmState (/usr/local/lib/node_modules/homebridge-envisalink/index.js:480:21)
    at EnvisalinkAccessory.processDelayedEvents (/usr/local/lib/node_modules/homebridge-envisalink/index.js:584:22)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by erfind** [comment]
http://forum.eyez-on.com/FORUM/viewtopic.php?f=6&t=5115&sid=45bf51c67d5c6daaf0a637a6454a1871

Firmware Change Log
Tue Jan 07, 2020 9:30 am

Updated 2021-03-03

Envisalink 4
Version 1.4.176 
- MAJOR REVISION
- V2 protocol of Envisalink Expansion bus. Affected backwards compatibility with expansion modules like Sidekick
- Envisalarms now signals central station when LTE backup enabled (power outage, Internet outage)
- Support for Honeywell NIGHT mode on both the portal and the App
- New local webservices added for DSC, Honeywell, and UNO.

**Comment by erfind** [comment]
They look like they also updated developer documents, but I don’t really know how to code to help implement this… :-/
 
http://forum.eyez-on.com/FORUM/download/file.php?id=223&sid=e26880ca8bb83e913d69d3a7bcaaf8a2

**Comment by erfind** [comment]
I'm going to close this as I wonder if there is an issue with homebridge. I started a new instance of Home Assistant and have no issue with connections. Sorry for the trouble.
