### ISSUE TITLE
Error unable to install

### ISSUE THREAD

**Issue by shaman101** [dustindclark/homebridge-envisalink#77]
Hi,

Was migrating to a new homebridge server, and failed to install Envisalink. Unusual error which I was ineffective in googling. 

ERROR LOADING PLUGIN homebridge-envisalink:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /homebridge/node_modules/homebridge-envisalink/node_modules/dateformat/lib/dateformat.js
require() of ES modules is not supported.
require() of /homebridge/node_modules/homebridge-envisalink/node_modules/dateformat/lib/dateformat.js from /homebridge/node_modules/homebridge-envisalink/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename dateformat.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /homebridge/node_modules/homebridge-envisalink/node_modules/dateformat/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-envisalink/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)

Any suggestions on what is going on here? Migrating to a synology homebridge setup via docker.

**Comment by dustindclark** [comment]
Duplicates #79, which is fixed in the latest version of the plugin.
