### ISSUE TITLE
PlugIn Won't Load - IMPORT Dateformat.js error

### ISSUE THREAD

**Issue by GitWhatsUp** [dustindclark/homebridge-envisalink#79]
ERROR LOADING PLUGIN homebridge-envisalink:
[28/09/2021, 19:01:21] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/homebridge-envisalink/node_modules/dateformat/lib/dateformat.js
require() of ES modules is not supported.
require() of /usr/local/lib/node_modules/homebridge-envisalink/node_modules/dateformat/lib/dateformat.js from /usr/local/lib/node_modules/homebridge-envisalink/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename dateformat.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/lib/node_modules/homebridge-envisalink/node_modules/dateformat/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)

**Comment by seabonthron** [comment]
This seems to be a general overall issue as myself and a few others are getting this same error.

**Comment by dustindclark** [comment]
Can you guys send the version of home bridge and node js that you're on? I can't recreate.

Dustin

**Comment by seabonthron** [comment]
I'm running homebridge v1.3.4 and node.js v14.17.4 on a Raspberry Pi Zero W

**Comment by GitWhatsUp** [comment]
Current distro of Homekit Pi image in a Pi 4 2gb, have tried with and without updates

**Comment by dustindclark** [comment]
This was caused by a backwards incompatible change in a dependency (dateformat). Upgrading to the latest version (0.2.17) will force a downgrade to a compatible version.
