### ISSUE TITLE
No Entry Arming

### ISSUE THREAD

**Issue by donmoss1** [dustindclark/homebridge-envisalink#99]
I have just started using your wonderful plug in and would like to request that you consider adding *9 or No Entry Arming for DSC. We have used this feature with the EyezOn App and would like to be able to continue as it gives us an extra level of security at night.

**Comment by readylmay** [comment]
Just for my clarity - what does *9 do? Does it put it in a state where there is no entry delay on the alarm when doors are opened? 

Also - there is a config for custom strings that you can set for a switch - you could set would ever key sequence in there to provide this function to you.

**Comment by donmoss1** [comment]
Yes, *9  plus the user code puts the selected partition in no entry arming or the partition will  immediately sounds if a door is opened. I looked at the user command string but as I have 3 partitions I was not sure how to get the user defined command to do the *9 bit on partition 1. I am willing to try that and see where we get to. I really like the *9 as I went for years and did not know it was there. Sir, thanks for your help and I look forward to continuing to using your product. I am very new to home automation but not DSC. I have one or two other ideas I want to share as time permits. Thanks again.

**Comment by readylmay** [comment]
I am also just a fan and user of the plugin - @dustindclark is the creator and maintainer....

**Comment by dustindclark** [comment]
As of 1.0.7, arming to "Night" will arm the panel to stay with no entry delay. Arming to "Home" still has the previous behavior (arm with delay).

**Comment by donmoss1** [comment]
Dustin,

I just tested the DSC alarm at my home and night arming does not produce the same results as *9 or no entry arming. With no entry arming the system immediately go into alarm as soon as an exterior  door is opened. You know you are no entry armed as the red LED on the key pads flashes. This feature would prevent someone from getting into the interior of the structure without the alarm sounding and central station being called. I just think it is a nice feature that you might add. I continue to arm my house zone from the key pad or the EyezOn App. Thanks for your help and I will try to PayPal you next week.

Don

**Comment by dustindclark** [comment]
Yeah, there's some weirdness right now that I'm trying to figure out. The command is 032, but 032 asks for PIN. If I specify a PIN, I get a system error from the panel. Will keep you posted.

**Comment by donmoss1** [comment]
Dustin,

Just opened Homebridge and installed your update. Must have just got it since yesterday. I will test it as soon as I can and I hope we can continue this conversation. I just know that *9 + my code produces the correct results on the actual alarm keypad. Thanks for being so responsive and receptive to ideas.

Don

**Comment by donmoss1** [comment]
Dustin,

Got the following in my Homebridge log and of course I don’t have a clue. This was after I updated the pug in (1.0.10). I will send you anything else that looks abnormal. 

Thanks
Don

sendcommand 0321C6
[27/02/2022, 19:57:47] [Envisalink] System Error 024 has been detected.
[27/02/2022, 19:57:47] [Envisalink] Failed setting panel state to 2 Error: Command 0321 resulted in 024 error from alarm
    at /usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:372:28
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:304:9)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)

**Comment by donmoss1** [comment]
Dustin,

You got it. 1.0.13 fixed it and it armed as expected for *9. There is now no error in the log. 

Thanks
Don

**Comment by SourLemons5** [comment]
Hey Dustin, 1.0.13 seemed to reset the board when i tried it, i got a "system not ready" message and all the LEDs on the keypad turn off for a few seconds, with 1.0.14 the Night button doesn't error the panel but it arms as home (stay on the panel) rather than no entry on my 1832 panel with an EnvisaLink3. Hope this helps. I'm also a fan on the *9 functionality!

**Comment by dustindclark** [comment]
It's not working at the moment. I've rolled back the change in 1.0.14 while I'm testing. Hoping to have a fix out shortly, but it's a little more involved than I realized.

**Comment by SourLemons5** [comment]
thank you! i had this working a while back with a universal devices ISY HA box, i think i had to set it to arm stay, wait for the exit delay then send arm instant, doing it in that order didn't require a PIN, i couldn't figure out how to get it to arm instant outright (i think :) it was a while ago)

**Comment by dustindclark** [comment]
Ok, fixed for real this time in v1.1.0. Thank you @donmoss1 , for the donation! Very much appreciated.

**Comment by SourLemons5** [comment]
you rock! thank you!

**Comment by dustindclark** [comment]
@richardriley999 , are you GetRileyLink on PayPal? If so, I appreciate your donation as well! Also, are you on a Honeywell panel? If so, maybe I can close #59?

**Comment by SourLemons5** [comment]
hey, nope that's not me! but i just sent you a thank you :) and im on a DSC PC1832 board.

**Comment by dustindclark** [comment]
Oh gotcha. That guy said he was using a Honeywell panel in his message. Thanks for the contribution nonetheless! Greatly appreciated.

Dustin

**Comment by donmoss1** [comment]
Good Morning,

I just wanted to touch base on another issue. I thought I would do it here rather than going to the web site. Home Kit will allow me to add any of my three partitions to my home kit favorites list. The option to “show in favorites” is not available for the zones such as windows, doors, etc. It would be nice to have a choice to include certain alarm indicators in my favorite section then one glance will tell me my home status. If you would like me to open a new issue just tell me.

Thanks 
Don

**Comment by dustindclark** [comment]
I think that's just a decision Apple made with the Home app...nothing I can really do in the plugin. Note, however, that open contact sensors will appear at the top of the Home tab (above favorites).

Dustin

**Comment by donmoss1** [comment]
Good Morning again,

Very neat. Thanks. A 76 year old dog can learn new tricks.

Don

**Comment by donmoss1** [comment]
Dustin,

I keep getting the error below and I don’t know why. If I am doing something wrong please tell me. If it is being caused by my panel or by the EnvisaLink 4 I would like to know that. 

Thanks for your help
Don Moss

Copied from Homebridge Log

[08/05/2022, 20:40:24] [Envisalink] Panel has requested code (900 response). Sending PIN...
[08/05/2022, 20:40:27] [Envisalink] Failed setting panel state to 1 Error: Command 0303 resulted in 024 error from alarm
    at /usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:393:28
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:316:9)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
[08/05/2022, 20:40:44] [Envisalink] Panel has requested code (900 response). Sending PIN...
[08/05/2022, 20:40:45] [Envisalink] Failed setting panel state to 1 Error: Command 0302 resulted in 018 error from alarm
    at /usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:393:28
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:316:9)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)

**Comment by readylmay** [comment]
You are getting error 24 from the API when trying to arm the system. See below - looks like your system is not ready to arm, by pass an open zone?

API Error Code 24

24 - API System Not Ready to Arm (system is either not-secure, in exit-delay, or already armed)


On May 10, 2022, at 9:17 AM, donmoss1 ***@***.***> wrote:

﻿

Dustin,

I keep getting the error below and I don’t know why. If I am doing something wrong please tell me. If it is being caused by my panel or by the EnvisaLink 4 I would like to know that.

Thanks for your help
Don Moss

Copied from Homebridge Log

[08/05/2022, 20:40:24] [Envisalink] Panel has requested code (900 response). Sending PIN...
[08/05/2022, 20:40:27] [Envisalink] Failed setting panel state to 1 Error: Command 0303 resulted in 024 error from alarm
at /usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:393:28
at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:316:9)
at Socket.emit (node:events:390:28)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at Socket.Readable.push (node:internal/streams/readable:228:10)
at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
[08/05/2022, 20:40:44] [Envisalink] Panel has requested code (900 response). Sending PIN...
[08/05/2022, 20:40:45] [Envisalink] Failed setting panel state to 1 Error: Command 0302 resulted in 018 error from alarm
at /usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:393:28
at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:316:9)
at Socket.emit (node:events:390:28)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at Socket.Readable.push (node:internal/streams/readable:228:10)
at TCP.onStreamRead (node:internal/stream_base_commons:199:23)

**Comment by donmoss1** [comment]
Gentlemen,

Thanks for your help. I have found that with the many updates to homebridge recently the alarm can get out of sync with the plugin and cause an error. Home Kit showes the alarm OFF when in fact if is ARMED. This can cause the error I previously requested help with. The Alarm should be disarmed before doing any upgrade with the plugin or server. This is more evident when an alarm has more than one partition such as mine.

Don

**Comment by dustindclark** [comment]
024 means not ready to arm. See error codes here for specifics: https://github.com/dustindclark/homebridge-envisalink/blob/master/docs/EnvisaLinkTPI-1-08.pdf

Does that help?

Dustin
